/**
 * Tests for the reef map's style and the geography it draws.
 *
 * A malformed MapLibre paint expression is not a type error. It is a layer that
 * throws inside the renderer and quietly never appears, which on a map made
 * mostly of layers is the worst possible failure mode: the page looks like it
 * loaded. Nothing short of running the style spec's own validator catches that,
 * so that is what happens here - and because the radius expressions encode a
 * design decision ("a lone sighting is a small dot at national zoom"), they are
 * evaluated too, at the zooms that decision was made about.
 *
 * The basemap assertions guard the build artefact rather than the code. It is
 * generated by scripts/build_basemap.py, committed, and then never looked at
 * again; a bad regeneration would show up as a blank map long after the commit
 * that caused it.
 */
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import {
  createPropertyExpression,
  validateStyleMin,
  type StylePropertySpecification,
} from '@maplibre/maplibre-gl-style-spec'
import type { FeatureCollection, Point } from 'geojson'
import type { StyleSpecification } from 'maplibre-gl'

import {
  MALDIVES_BOUNDS,
  MAX_ZOOM,
  MIN_ZOOM,
  SEAFLOOR_SOURCE,
  SIGHTINGS_SOURCE,
  baseStyle,
  basemapLayers,
  coreRadius,
  haloRadius,
  severityColour,
  sightingLayers,
} from './mapStyle'

/**
 * A stand-in for the DOM token reader. Every value is a valid colour, because
 * that is all the style spec checks; which colour is a design question, not one a
 * test can answer.
 */
const read = (name: string) => (name === '--sea-abyss' ? '#03121c' : '#2ec8a2')

/** The whole style as the map is actually assembled, sources included. */
function fullStyle(hasRaster = false): StyleSpecification {
  const style = baseStyle(read, hasRaster ? 'https://tiles.invalid/{z}/{x}/{y}.png' : '', '')
  const empty: FeatureCollection = { type: 'FeatureCollection', features: [] }
  style.sources[SEAFLOOR_SOURCE] = { type: 'geojson', data: empty }
  style.sources[SIGHTINGS_SOURCE] = { type: 'geojson', data: empty }
  style.layers.push(...basemapLayers(read, hasRaster), ...sightingLayers(read))
  return style
}

/**
 * The property definitions the renderer compiles paint values against. Spelling
 * them out is what makes `createPropertyExpression` behave exactly as MapLibre
 * does - including rejecting an expression that reads a feature property in a
 * zoom-only slot.
 */
function propertySpec(type: 'number' | 'color'): StylePropertySpecification {
  return {
    type,
    'property-type': 'data-driven',
    expression: { interpolated: true, parameters: ['zoom', 'feature'] },
    transition: true,
    overridable: false,
  } as StylePropertySpecification
}

/** Evaluates a data-and-zoom-driven paint expression the way the renderer does. */
function evaluate(expression: unknown, zoom: number, count: number, severity = 0.5): number {
  const compiled = createPropertyExpression(expression, propertySpec('number'))
  if (compiled.result === 'error') {
    throw new Error(compiled.value.map((error) => error.message).join('; '))
  }
  return compiled.value.evaluate({ zoom }, { properties: { count, severity } } as never)
}

describe('map style', () => {
  it('is valid against the MapLibre style specification', () => {
    expect(validateStyleMin(fullStyle())).toEqual([])
  })

  it('is still valid with a raster basemap configured', () => {
    expect(validateStyleMin(fullStyle(true))).toEqual([])
  })

  it('stands the local fills down when a raster basemap is configured', () => {
    const ids = (hasRaster: boolean) => basemapLayers(read, hasRaster).map((layer) => layer.id)

    expect(ids(false)).toContain('sea-shelf')
    expect(ids(true)).not.toContain('sea-shelf')
    // The line work survives either way: it is annotation, not a basemap.
    expect(ids(true)).toContain('sea-reef')
  })

  it('paints unassessed sightings off the condition scale entirely', () => {
    const compiled = createPropertyExpression(severityColour(read), propertySpec('color'))
    expect(compiled.result).toBe('success')
  })

  it('draws worse condition on top', () => {
    const core = sightingLayers(read).find((layer) => layer.id === 'sightings-core')
    expect(core?.layout).toMatchObject({ 'circle-sort-key': ['get', 'severity'] })
  })
})

describe('marker radius', () => {
  it('keeps a lone sighting small enough to read as a point at national zoom', () => {
    // The complaint that started this: at national zoom the markers were large
    // enough to cover the atolls they sat on. Anything over ~3 px for a single
    // sighting is back in that territory.
    expect(evaluate(coreRadius(), MIN_ZOOM, 1)).toBeLessThanOrEqual(3)
  })

  it('grows with zoom for the same cluster', () => {
    const atZoom = (zoom: number) => evaluate(coreRadius(), zoom, 40)
    expect(atZoom(MIN_ZOOM)).toBeLessThan(atZoom(8))
    expect(atZoom(8)).toBeLessThan(atZoom(11))
    expect(atZoom(11)).toBeLessThan(atZoom(MAX_ZOOM - 1))
  })

  it('grows with cluster size at a fixed zoom', () => {
    const forCount = (count: number) => evaluate(coreRadius(), 8, count)
    expect(forCount(1)).toBeLessThan(forCount(50))
    expect(forCount(50)).toBeLessThan(forCount(500))
  })

  it('never lets a national-zoom cluster cover a whole atoll', () => {
    // Half a degree of latitude is about 12 px at zoom 5, and the smallest
    // Maldivian atoll platform is smaller than that.
    expect(evaluate(coreRadius(), MIN_ZOOM, 500)).toBeLessThan(8)
  })

  it('keeps the halo bigger than the core it sits under', () => {
    for (const zoom of [MIN_ZOOM, 8, 11, 14]) {
      for (const count of [1, 50, 500]) {
        expect(evaluate(haloRadius(), zoom, count)).toBeGreaterThan(
          evaluate(coreRadius(), zoom, count),
        )
      }
    }
  })
})

describe('bundled geography', () => {
  const basemap = JSON.parse(
    readFileSync(fileURLToPath(new URL('../../public/basemap/maldives.json', import.meta.url)), {
      encoding: 'utf-8',
    }),
  ) as FeatureCollection
  // The build script always writes a 2D bbox; the GeoJSON type allows 3D too.
  const clipBox = basemap.bbox as [number, number, number, number]

  const kinds = new Set(basemap.features.map((feature) => String(feature.properties?.kind)))

  it('carries every kind the style draws', () => {
    for (const kind of ['slope', 'shelf', 'reef', 'island']) {
      expect(kinds).toContain(kind)
    }
  })

  it('names all twenty administrative atolls, plus the capital', () => {
    const atolls = basemap.features.filter((feature) => feature.properties?.kind === 'atoll')
    expect(atolls).toHaveLength(20)
    expect(atolls.every((feature) => feature.properties?.name && feature.properties?.code)).toBe(
      true,
    )
    expect(kinds).toContain('capital')
  })

  it('places every atoll label inside the view the map opens on', () => {
    // A label outside the initial bounds is a label nobody will ever see, and the
    // likeliest sign that a coordinate was mistyped.
    const [[west, south], [east, north]] = MALDIVES_BOUNDS as [
      [number, number],
      [number, number],
    ]
    for (const feature of basemap.features) {
      if (feature.properties?.kind !== 'atoll') continue
      const [lon, lat] = (feature.geometry as Point).coordinates
      expect(lon, String(feature.properties?.name)).toBeGreaterThan(west)
      expect(lon, String(feature.properties?.name)).toBeLessThan(east)
      expect(lat, String(feature.properties?.name)).toBeGreaterThan(south)
      expect(lat, String(feature.properties?.name)).toBeLessThan(north)
    }
  })

  it('stays inside the box it was clipped to', () => {
    const [west, south, east, north] = clipBox
    let checked = 0

    const walk = (coordinates: unknown) => {
      if (typeof (coordinates as number[])[0] === 'number') {
        const [lon, lat] = coordinates as [number, number]
        expect(lon).toBeGreaterThanOrEqual(west)
        expect(lon).toBeLessThanOrEqual(east)
        expect(lat).toBeGreaterThanOrEqual(south)
        expect(lat).toBeLessThanOrEqual(north)
        checked += 1
        return
      }
      for (const part of coordinates as unknown[]) walk(part)
    }

    for (const feature of basemap.features) {
      walk((feature.geometry as { coordinates: unknown }).coordinates)
    }
    // Guards the guard: a build that emitted empty geometries would otherwise
    // pass every assertion above by never running one.
    expect(checked).toBeGreaterThan(1000)
  })
})
